"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { useState } from "react";
import Documents from "@/components/documents";
import Contact from "@/components/contact";
import Connexion from "@/components/connexion";
import Home from "@/components/home";
import Header from "@/components/header";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const [page, setPage] = useState("accueil");

    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <Header setPage={setPage} />
                <main className="bg-gray-100 min-h-screen flex flex-col items-center justify-center">
                    {/* {children} */}
                    {/* {page === "accueil" && <Home />}
                    {page === "documents" && <Documents />}
                    {page === "contact" && <Contact />}
                    {page === "connexion" && <Connexion />} */}

                    {page === "accueil" ? (
                        <Home />
                    ) : page === "documents" ? (
                        <Documents />
                    ) : page === "contact" ? (
                        <Contact />
                    ) : page === "connexion" ? (
                        <Connexion />
                    ) : (
                        <Home />
                    )}
                </main>
            </body>
        </html>
    );
}
